Repository ponylang/corral, pull requests merged in 2019-11, with the labels that each got.

#52 Rename bundle.json to corral.json
  corral/bundle/bundle.pony
  corral/main.pony
  corral/test/corral.json
  doc/design.md
  doc/questions_notes.md
Labels: triggers release

#53 Add --path flag
  corral/bundle/bundle.pony
  corral/cmd/cmd_add.pony
  corral/cmd/cmd_clean.pony
  corral/cmd/cmd_fetch.pony
  corral/cmd/cmd_info.pony
  corral/cmd/cmd_init.pony
  corral/cmd/cmd_list.pony
  corral/cmd/cmd_remove.pony
  corral/cmd/cmd_run.pony
  corral/cmd/cmd_update.pony
  corral/cmd/context.pony
  corral/main.pony
  corral/test/main.pony
Labels: changelog - added

#57 Fix `corral run` should work if there is no corral.json
  corral/cmd/cmd_run.pony
  corral/cmd/context.pony
  corral/main.pony
Labels: changelog - fixed

#56 Fix Corral run only looking for binaries on $PATH
  corral/cmd/cmd_run.pony
  corral/util/action.pony
  corral/util/shell.pony
  corral/vcs/git.pony
Labels: changelog - fixed

#60 Improved testing and more
  .gitignore
  Makefile
  corral/bundle/bundle.pony
  corral/bundle/data.pony
  corral/bundle/dep.pony
  corral/bundle/json.pony
  corral/cli.pony
  corral/cmd/cmd_add.pony
  corral/cmd/cmd_clean.pony
  corral/cmd/cmd_fetch.pony
  corral/cmd/cmd_info.pony
  corral/cmd/cmd_init.pony
  corral/cmd/cmd_list.pony
  corral/cmd/cmd_remove.pony
  corral/cmd/cmd_run.pony
  corral/cmd/cmd_update.pony
  corral/cmd/constraints.pony
  corral/cmd/context.pony
  corral/main.pony
  corral/semver/solver/in_mem_artifact_source.pony
  corral/semver/solver/result.pony
  corral/test/integration/test_clean.pony
  corral/test/integration/test_fetch.pony
  corral/test/integration/test_help.pony
  corral/test/integration/test_info.pony
  corral/test/integration/test_run.pony
  corral/test/integration/test_update.pony
  corral/test/integration/test_version.pony
  corral/test/integration/util.pony
  corral/test/main.pony
  corral/test/test_bundle.pony
  corral/test/test_git.pony
  corral/test/testdata/abitofeverything/corral.json
  corral/test/testdata/bad-json/corral.json
  corral/test/testdata/empty-deps/corral.json
  corral/test/testdata/empty-dir/.gitkeep
  corral/test/testdata/empty-file/corral.json
  corral/test/testdata/github-leaf/corral.json
  corral/test/testdata/github-real/corral.json
  corral/test/testdata/github-real/lock.json
  corral/test/testdata/local-git/corral.json
  corral/test/testdata/local/corral.json
  corral/test/testdata/mutually-recursive/bar/corral.json
  corral/test/testdata/mutually-recursive/foo/corral.json
  corral/test/testdata/nested/corral.json
  corral/test/testdata/nested/deeply/corral.json
  corral/test/testdata/nested/empty/.gitkeep
  corral/test/testdata/self-referential/corral.json
  corral/util/log.pony
  corral/vcs/_test.pony
  corral/vcs/bzr.pony
  corral/vcs/git.pony
  corral/vcs/hg.pony
  corral/vcs/svn.pony
  corral/vcs/vcs.pony
Labels: changelog - fixed
