Repository ponylang/corral, pull requests merged in 2020-05, with the labels that each got.

#89 Update to handle new `ProcessError` types
  corral/test/util.pony
  corral/util/action.pony
Labels: do not merge

#91 Add FreeBSD support
  .ci-scripts/freebsd-install-pony-tools.bash
  .ci-scripts/release/x86-64-unknown-freebsd12.1-nightly.bash
  .ci-scripts/release/x86-64-unknown-freebsd12.1-release.bash
  .cirrus.yml
Labels: changelog - added

#111 Rename FreeBSD artifacts
  .ci-scripts/freebsd-12.1-install-pony-tools.bash
  .ci-scripts/freebsd-install-pony-tools.bash
  .ci-scripts/release/x86-64-unknown-freebsd-12.1-nightly.bash
  .ci-scripts/release/x86-64-unknown-freebsd-12.1-release.bash
  .cirrus.yml
Labels: changelog - changed

#115 Remove extraneous CR in outputs on Windows
  corral/util/action.pony
Labels: changelog - fixed

#117 Use correct path separator in PONYPATH on Windows
  corral/cmd/cmd_run.pony
Labels: changelog - fixed
